version: '3'
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=url-shortener
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db